apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: IMAGE_SERVICE_2
          ports:
            - containerPort: 8002